### ISSUE TITLE
After

### ISSUE THREAD

**Issue by Hantoo** [nickmcdonald/ies-generator#8]
Issue adding modifier and operation after adjusting vertical resolution.
![2019-02-08_13-58-26](https://user-images.githubusercontent.com/1647342/52482703-e43a3c80-2ba9-11e9-924d-ab1fc6c07f74.gif)

Would be nice to include a prebuilt .exe in the res.

**Comment by nickNedieon** [comment]
Hi Hantoo,
There are prebuilt exes at https://github.com/nickmcdonald/ies-generator/releases, and I recommend you use those instead.

There are some issues with the source code at the moment. I was half way through adding more features and i got distracted, and haven't got around to finishing it yet.

thank for your interest
