### ISSUE TITLE
Does not import to Unreal Engine (4.24)

### ISSUE THREAD

**Issue by kissklas** [nickmcdonald/ies-generator#9]
I have to run the profile through another generator to make it import, but that generator only exported the lower half of the IES. Had a look at the ascii but could make no sense of what was the issue, except that the values beween exports was completely different.

**Comment by nickmcdonald** [comment]
Thanks for trying my software! But I am not updating this project anymore. Please check out [cndl.io](https://cndl.io) It is a better version of this app that I made. It is also free to use.
